services:
    Drjele\Symfony\Console\Command\CronjobCreateCommand:
        arguments:
            $confGenerateService: '@Drjele\Symfony\Console\Service\ConfGenerateService'
            $config: '%drjele_symfony_console.cronjob%'
        tags:
            - {name: 'console.command'}

    Drjele\Symfony\Console\Command\WorkerCreateCommand:
        arguments:
            $confGenerateService: '@Drjele\Symfony\Console\Service\ConfGenerateService'
            $config: '%drjele_symfony_console.worker%'
        tags:
            - {name: 'console.command'}

    Drjele\Symfony\Console\Service\ConfGenerateService:
        arguments:
            $templates: !tagged_iterator drjele.symfony.console.template

    Drjele\Symfony\Console\Template\CrontabTemplate:
        tags:
            - {name: 'drjele.symfony.console.template'}

    Drjele\Symfony\Console\Template\SupervisorTemplate:
        tags:
            - {name: 'drjele.symfony.console.template'}
